const { test, expect } = require('@playwright/test');
const engineer = 'test-engineer-credential-with-at-least-32-characters';
const approver = 'test-approver-credential-with-at-least-32-characters';
async function login(page, token) { await page.getByLabel('Operations credential').fill(token); await page.getByRole('button', { name: 'Sign in', exact: true }).click(); await expect(page.getByRole('button', { name: 'Sign out', exact: true })).toBeVisible(); }
async function status(page, value) { await expect(page.getByTestId('canonical-status')).toHaveText(value, { timeout: 20000 }); }
async function create(page, title) { await page.goto('/'); await login(page, engineer); await page.locator('textarea').first().fill(title); await page.getByRole('button', { name: /Run investigation/ }).dblclick(); await expect(page).toHaveURL(/\/incidents\/[a-f0-9]{24}$/); }
test('real browser central journey survives navigation/reload, preserves history and deep links', async ({ page }) => {
 await create(page, 'Browser journey incident'); const bookmark = page.url(); await status(page, 'Investigating');
 await page.getByRole('button', { name: 'Incidents', exact: true }).click(); await expect(page).toHaveURL(/\/incidents$/); await page.goBack(); await expect(page).toHaveURL(bookmark); await page.reload();
 await status(page, 'Awaiting review'); await page.locator('main[aria-label="Incident engineering workspace"] details').first().locator('summary').click(); await expect(page.getByText('software-engineering · completed ·', { exact: false })).toBeVisible();
 await page.getByLabel('Decision notes', { exact: true }).fill('Reviewed test fixture source evidence'); await page.getByLabel('Completed investigation').selectOption({ index: 1 }); await page.getByLabel('Evidence URL', { exact: true }).fill('https://example.test/logs'); await page.getByLabel('Evidence observation', { exact: true }).fill('Observed original failure'); await page.getByRole('button', { name: 'Accept findings', exact: true }).click();
 const form = page.getByRole('form', { name: 'Create remediation proposal' }); await expect(form).toBeVisible();
 for (const field of ['title', 'action', 'rationale', 'validationPlan', 'target', 'owner']) await form.getByLabel(`Proposal ${field}`, { exact: true }).fill(field === 'title' ? 'Recovery proposal' : `Test ${field}`);
 await form.getByRole('button', { name: 'Create proposal', exact: true }).click(); await status(page, 'Remediation planned');
 await page.getByLabel('Edit proposal owner').fill('Assigned test engineer'); await page.getByRole('button', { name: 'Save draft changes' }).click(); await expect(page.getByText('Assigned test engineer · pending', { exact: false })).toBeVisible();
 await page.getByRole('button', { name: 'Sign out', exact: true }).click(); await login(page, approver); await page.reload(); await status(page, 'Remediation planned'); await page.getByLabel('Decision notes', { exact: true }).fill('Approved risk and validation plan'); await page.getByRole('button', { name: 'Approve proposal', exact: true }).click();
 await expect(page.getByRole('button', { name: 'Begin manual remediation' })).toBeVisible(); await page.getByRole('button', { name: 'Begin manual remediation' }).click(); await status(page, 'In remediation');
 await page.getByLabel('Approved proposal', { exact: true }).selectOption({ index: 1 }); await page.getByLabel('Change reference URL').fill('https://example.test/change'); await page.getByLabel('Performed by', { exact: true }).fill('External engineer'); await page.getByLabel('Performed at', { exact: true }).fill('2026-09-30T10:00'); await page.getByLabel('Decision notes', { exact: true }).fill('Changed timeout handling externally'); await page.getByRole('button', { name: 'Record manual change' }).click(); await status(page, 'Verifying');
 await page.getByLabel('Verification criteria').fill('Original timeout does not recur'); await page.getByLabel('Verification evidence URL').fill('https://example.test/recovery'); await page.getByLabel('Verification observation').fill('Manually observed recovery in fixture evidence'); await page.getByRole('button', { name: 'Record inconclusive' }).click(); await expect(page.getByRole('button', { name: 'Confirm resolution' })).toBeDisabled();
 await page.getByRole('button', { name: 'Record failed', exact: true }).click(); await status(page, 'In remediation'); await page.getByLabel('Change reference URL').fill('https://example.test/revised-change'); await page.getByRole('button', { name: 'Record manual change' }).click(); await status(page, 'Verifying');
 await page.getByRole('button', { name: 'Record passed', exact: true }).click(); await page.getByLabel('Outstanding risks').fill('Continue monitoring'); await page.getByRole('button', { name: 'Confirm resolution' }).click(); await status(page, 'Resolved');
 await page.getByLabel('Post-incident report').fill('# Lessons\nBrowserjourney recovery and prevention.'); await page.getByRole('button', { name: 'Save report draft' }).click(); await page.getByRole('button', { name: 'Approve latest report' }).click(); await page.getByRole('button', { name: 'Index approved report', exact: true }).click(); await expect(page.getByText('Indexed knowledge document', { exact: false })).toBeVisible();
 await page.getByLabel('Decision notes', { exact: true }).fill('Recurrence requires a new investigation'); await page.getByRole('button', { name: 'Reopen incident' }).click(); await status(page, 'Open'); await page.getByRole('button', { name: 'Request targeted reinvestigation' }).click(); await status(page, 'Investigating'); await page.reload(); await status(page, 'Awaiting review'); await expect(page.getByText('Recurrence requires a new investigation', { exact: true }).first()).toBeVisible();
 await page.goto('/incidents'); await expect(page.getByText('Browser journey incident', { exact: true })).toBeVisible(); await page.goto(bookmark); await status(page, 'Awaiting review'); await page.goBack(); await expect(page).toHaveURL(/\/incidents$/); await page.goForward(); await expect(page).toHaveURL(bookmark); await status(page, 'Awaiting review');
 await page.screenshot({ path: 'test-results/incident-desktop.png', fullPage: true }); await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: 'test-results/incident-mobile.png', fullPage: true });
});

test('rejected findings do not authorize planning; cancellation and expired browser access remain recoverable', async ({ page, context }) => {
 await create(page, 'Browser rejection incident'); const bookmark = page.url(); await status(page, 'Awaiting review');
 await page.getByLabel('Decision notes', { exact: true }).fill('Unsupported hypothesis rejected'); await page.getByLabel('Completed investigation').selectOption({ index: 1 }); await page.getByLabel('Evidence URL', { exact: true }).fill('https://example.test/rejection'); await page.getByLabel('Evidence observation', { exact: true }).fill('Source does not establish the claimed cause'); await page.getByRole('button', { name: 'Reject findings', exact: true }).click();
 await expect(page.getByRole('form', { name: 'Create remediation proposal' })).toHaveCount(0);
 await page.getByRole('button', { name: 'Request targeted reinvestigation' }).click(); await status(page, 'Investigating'); await page.getByRole('button', { name: 'Cancel investigation' }).click(); await status(page, 'Open');
 const cookies = await context.cookies(); const session = cookies.find(cookie => cookie.name === 'ops_session'); await context.addCookies([{ ...session, expires: 1 }]); await page.reload();
 await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible(); await expect(page.getByRole('alert').filter({ hasText: /session expired|authorization required/ }).first()).toBeVisible();
 await login(page, engineer); await status(page, 'Open'); await expect(page.getByRole('alert').filter({ hasText: /session expired|authorization required/ })).toHaveCount(0); await page.reload(); await status(page, 'Open'); await expect(page).toHaveURL(bookmark);
 await page.goto('/incidents/not-an-id'); await expect(page.getByRole('heading', { name: 'Page not found' })).toBeVisible();
});
