const { test, expect } = require('@playwright/test'); const { createHmac } = require('node:crypto');
test.beforeEach(async ({ request }) => { const r = await request.post('http://127.0.0.1:5050/__test/isolate-actors', { data: { label: require('node:crypto').randomUUID() } }); expect(r.status()).toBe(200); });
const engineer = 'test-engineer-credential-with-at-least-32-characters', approver = 'test-approver-credential-with-at-least-32-characters';
async function login(page, token) { await page.getByLabel('Operations credential').fill(token); await page.getByRole('button', { name: 'Sign in', exact: true }).click(); await expect(page.getByRole('button', { name: 'Sign out', exact: true })).toBeVisible(); }
test('authenticated signal to retained evidence, reviewed change, measured comparison and semantic source in real browser', async ({ page, request }) => {
 const payload = { repository: { full_name: 'fixture/repo' }, action: 'completed', workflow_run: { id: 321, name: 'Browser fixture workflow failure', conclusion: 'failure', head_sha: 'a'.repeat(40), head_branch: 'main', run_attempt: 1, completed_at: '2026-01-01T00:00:00Z' } };
 const signature = `sha256=${createHmac('sha256', 'test-github-signature-secret-with-32-characters').update(JSON.stringify(payload)).digest('hex')}`;
 const delivery = await request.post('http://127.0.0.1:5050/api/signals/github', { data: payload, headers: { 'X-GitHub-Event': 'workflow_run', 'X-GitHub-Delivery': 'browser-fixture-delivery', 'X-Hub-Signature-256': signature } }); expect(delivery.status()).toBe(202);
 await page.goto('/'); await login(page, engineer); await page.getByRole('button', { name: 'Engineering', exact: true }).click(); await expect(page.getByText(/workflow-failure: Browser fixture/)).toBeVisible(); await page.getByRole('button', { name: 'Investigate signal', exact: true }).click(); await expect(page).toHaveURL(/\/incidents\/[a-f0-9]{24}$/);
 const id = page.url().split('/').pop(); await expect(page.getByTestId('canonical-status')).toHaveText('Awaiting review', { timeout: 20000 });
 await page.locator('details').filter({ has: page.getByText('github.job-log · available', { exact: false }) }).locator('summary').first().click();
 await expect(page.getByText('github.job-log · available', { exact: false })).toBeVisible();
 const sources = await (await request.get(`http://127.0.0.1:5050/api/evidence/incidents/${id}`, { headers: { Authorization: `Bearer ${engineer}` } })).json(); expect(sources.items.some(e => e.type === 'job-log' && e.runId)).toBeTruthy(); expect(JSON.stringify(sources)).not.toContain('password=fixture-secret');
 await page.getByLabel('Decision notes', { exact: true }).fill('Reviewed retained provider evidence'); await page.getByLabel('Completed investigation').selectOption({ index: 1 }); await page.getByLabel('Evidence URL', { exact: true }).fill('https://github.com/fixture/repo/actions/runs/321'); await page.getByLabel('Evidence observation', { exact: true }).fill('Observed fixture failing assertion'); await page.getByRole('button', { name: 'Accept findings', exact: true }).click();
 const form = page.getByRole('form', { name: 'Create remediation proposal' }); await expect(form).toBeVisible();
 for (const field of ['title', 'action', 'rationale', 'validationPlan', 'target', 'owner']) await form.locator(`[name="${field}"]`).fill(`Fixture ${field}`); await form.getByRole('button', { name: 'Create proposal', exact: true }).click(); await expect(page.getByRole('button', { name: 'Save draft changes', exact: true })).toBeVisible();
 await page.getByRole('button', { name: 'Sign out', exact: true }).click(); await login(page, approver); await page.getByLabel('Decision notes', { exact: true }).fill('Approved fixture proposal'); await page.getByRole('button', { name: 'Approve proposal', exact: true }).click(); await expect(page.getByRole('button', { name: 'Begin manual remediation', exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Begin manual remediation', exact: true }).click();
 await page.getByLabel('Approved proposal', { exact: true }).selectOption({ index: 1 }); await page.getByLabel('Change reference URL', { exact: true }).fill('https://github.com/fixture/repo/commit/' + 'a'.repeat(40)); await page.getByLabel('Performed by', { exact: true }).fill('Fixture engineer'); await page.getByLabel('Performed at', { exact: true }).fill('2026-01-01T02:30'); await page.getByLabel('Decision notes', { exact: true }).fill('Recorded actual test-only change'); await page.getByRole('button', { name: 'Record manual change', exact: true }).click(); await expect(page.getByTestId('canonical-status')).toHaveText('Verifying');
 const measurementForm = page.locator('form').filter({ has: page.getByRole('button', { name: 'Retrieve measured verification', exact: true }) });
 await measurementForm.locator('[name="resourceId"]').fill('/subscriptions/fixture/resource'); await measurementForm.locator('[name="metric"]').fill('Errors'); await measurementForm.locator('[name="aggregation"]').selectOption('Total');
 for (const [field, value] of Object.entries({ baselineStart: '2026-01-01T00:00', baselineEnd: '2026-01-01T00:10', currentStart: '2026-01-01T03:00', currentEnd: '2026-01-01T03:10' })) await measurementForm.locator(`[name="${field}"]`).fill(value);
 await measurementForm.locator('[name="threshold"]').fill('5'); await measurementForm.getByRole('button').click(); await expect(page.getByText(/^passed ·/)).toBeVisible(); await expect(page.getByTestId('canonical-status')).toHaveText('Verifying');
 const ingested = await request.post('http://127.0.0.1:5050/api/knowledge', { headers: { Authorization: `Bearer ${engineer}` }, data: { title: 'Browser source runbook', text: '# Failure\nInspect workflow assertion and measured error totals.', sourceUrl: 'https://github.com/fixture/repo/blob/main/README.md' } }); expect(ingested.status()).toBe(201);
 await page.getByRole('button', { name: 'Knowledge', exact: true }).click(); await page.getByRole('button', { name: 'Load indexed sources', exact: true }).click(); await expect(page.getByText(/Browser source runbook/).first()).toBeVisible(); await page.getByLabel('Query', { exact: true }).fill('workflow assertion'); await page.getByRole('button', { name: 'Search', exact: true }).click(); await expect(page.getByText(/local_semantic score/).first()).toBeVisible();
 await page.goto(`/incidents/${id}`); await expect(page.getByTestId('canonical-status')).toHaveText('Verifying'); await expect(page.getByText(/^passed ·/)).toBeVisible();
});
