import { useEffect, useState } from 'react'
import { getSignals, associateSignal, type EngineeringSignal } from '../../services/api'
export default function Signals() {
 const [items, setItems] = useState<EngineeringSignal[]>([]), [error, setError] = useState(''), [target, setTarget] = useState(''), [busy, setBusy] = useState(false)
 const load = async () => { try { setItems((await getSignals()).items); setError('') } catch (e) { setError(e instanceof Error ? e.message : 'Signals unavailable') } }
 useEffect(() => { const initial = setTimeout(() => void load(), 0); const auth = () => { setItems([]); void load() }; const expired = () => { setItems([]); setError('Sign in to inspect signals') }; window.addEventListener('ops-auth-changed', auth); window.addEventListener('ops-session-expired', expired); return () => { clearTimeout(initial); window.removeEventListener('ops-auth-changed', auth); window.removeEventListener('ops-session-expired', expired) } }, [])
 const link = async (signal: EngineeringSignal, investigate: boolean) => { setBusy(true); try { const incident = await associateSignal(signal.signalId, signal.incidentId || target || undefined, investigate); await load(); window.history.pushState({}, '', `/incidents/${incident._id}`); window.dispatchEvent(new PopStateEvent('popstate')) } catch (e) { setError(e instanceof Error ? e.message : 'Association failed') } finally { setBusy(false) } }
 return <section className="phase2-workspace"><h2>Engineering signals</h2><p>Authenticated observed events. A failure or nearby commit does not establish causation.</p>{error && <p role="alert">{error}</p>}<button disabled={busy} onClick={() => void load()}>Refresh signals</button><label>Existing incident ID (optional)<input value={target} onChange={e => setTarget(e.target.value)} /></label>{!error && !items.length && <p>No persisted signals.</p>}{items.map(s => <article key={s.signalId}><h3>{s.summary}</h3><p>{s.provider} · {s.severity} · {new Date(s.observedAt).toLocaleString()} · {s.state}</p><a href={s.references.sourceUrl} target="_blank" rel="noreferrer">Source</a>{s.incidentId && <a href={`/incidents/${s.incidentId}`}>Linked incident</a>}<button disabled={busy} onClick={() => void link(s, false)}>{s.incidentId ? 'Open incident' : target ? 'Attach to incident' : 'Create incident'}</button><button disabled={busy} onClick={() => void link(s, true)}>Investigate signal</button></article>)}</section>
}
